import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.bbu.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=4&tabIndex=1")
    page.get_by_text("Filter").click()
    page.locator("#alerts-filterId").get_by_text("Alerts").click()
    page.locator(".dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Over Bias$")).nth(1).click()
    page.locator(".dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Under Bias$")).nth(1).click()
    page.locator(".dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^MAPE$")).nth(1).click()
    page.locator(".dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Stability$")).nth(1).click()
    page.locator(".dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^FVA$")).nth(1).click()
    page.get_by_role("button", name="columns").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("treeitem", name="6W-Actuals Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="User Bias Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.locator(".pointer.zeb-adjustments").click()
    page.get_by_text("Save Preference").click()
    with page.expect_download() as download_info:
        page.locator(".icon-color-toolbar-active.zeb-download-underline").click()
    download = download_info.value
    page.locator(".pointer.zeb-adjustments").click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-icon.ag-icon-filter").first.click()
    page.get_by_role("textbox", name="Filter Value").fill("WINCO")
    page.get_by_role("button", name="Apply").click()
    page.locator(".ag-icon.ag-icon-filter").first.click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.icon-small-dropdown > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.get_by_text("In progress").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.icon-small-dropdown > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.get_by_text("Completed").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.icon-small-dropdown > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.get_by_text("Not started").click()
    page.get_by_role("treegrid").get_by_text("WALMART STORES HQ").dblclick()
    page.locator("span").filter(has_text="WALMART").first.dblclick()
    page.get_by_role("treegrid").get_by_text("WALMART 0906 SC B-0006805-01-").dblclick()
    page.get_by_text("WALMART 0906 SC B-0006805-01-").click(button="right")
    page.get_by_text("Drill up").click()
    page.locator(".ag-row-even.ag-row-focus.ag-row-not-inline-editing.ag-row.ag-row-level-0.ag-row-position-absolute.ag-row-first.ag-row-hover > .ag-cell-value > .ag-cell-wrapper").click(button="right")
    page.get_by_text("Drill up").click()
    page.get_by_role("treegrid").get_by_text("WALMART STORES HQ").click(button="right")
    page.get_by_text("Drill up").click()
    page.get_by_role("columnheader", name="6W-Actuals").click()
    page.locator("a").filter(has_text="2").click()
    page.locator(".zeb-nav-to-first").click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)   WALMART STORES HQ").get_by_label("Press Space to toggle row").check()
    page.locator(".checkbox-primary-color").first.uncheck()
    page.locator(".checkbox-primary-color").first.check()
    page.locator(".d-flex.align-items-center.checkbox-primary-color").first.uncheck()
    page.locator(".ag-row-odd > .ag-cell-value > .ag-cell-wrapper > .ag-group-value > aeap-group-cell-renderer > .d-flex.align-items-center.w-fit-content > .d-flex").first.uncheck()
    page.get_by_role("button", name="columns").nth(1).click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("User Bias")
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("button", name="columns").nth(1).click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    with page.expect_download() as download1_info:
        page.locator("div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download1 = download1_info.value
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.get_by_role("spinbutton", name="Filter Value").fill("761")
    page.get_by_label("Column Filter").get_by_role("button", name="Apply").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button.ag-filter-active > .ag-icon").click()
    page.get_by_label("Column Filter").get_by_role("button", name="Reset").click()
    page.locator(".checkbox-primary-color").first.check()
    page.locator("span").filter(has_text="ENTENMANNS").first.dblclick()
    page.locator("span").filter(has_text="EN BITES").first.dblclick()
    page.get_by_text("EN LITTLE BITES CP").first.dblclick()
    page.get_by_text("EN LB CHOCCH MFN 10P-").first.click(button="right")
    page.get_by_text("Drill up").click()
    page.get_by_role("gridcell").filter(has_text=re.compile(r"^$")).first.click(button="right")
    page.get_by_role("gridcell").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("esp-card-component").filter(has_text="Products10 rows out of 11").locator("a").click()
    page.locator("div:nth-child(3) > esp-pagination-v2 > .d-flex.w-100 > .pagination-pager > .pagination-first > .zeb-nav-to-first").click()
    page.get_by_role("button", name="Apply").click()
    page.locator("div").filter(has_text=re.compile(r"^Filter$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 5 Next 4$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 5 Next 12$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 13 Next 4$")).nth(1).click()
    page.locator("esp-card-component").filter(has_text="Weekly Summary Customer:").get_by_role("button").click()
    page.get_by_role("treeitem", name="-11-02 (45) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="-11-09 (46) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="-11-16 (47) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("div:nth-child(4) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator("div:nth-child(4) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    with page.expect_download() as download2_info:
        page.locator("div:nth-child(3) > #export-iconId > .icon-color-toolbar-active").click()
    download2 = download2_info.value
    page.locator(".align-middle").first.click()
    page.get_by_text("Event").nth(1).click()
    page.locator("esp-card-component").filter(has_text="Event Details columns (0)").get_by_role("button").click()
    page.get_by_role("treeitem", name="Event Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="UPC 12 Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="Customer Level 2 Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="Start Date Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="End Date Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="Max Promo Price Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="Min Promo Price Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("UPC")
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (visible)").uncheck()
    page.locator("div:nth-child(7) > div > esp-grid-container > esp-card-component > .card-container > .title > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div:nth-child(2) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    with page.expect_download() as download3_info:
        page.locator("div:nth-child(7) > div > esp-grid-container > esp-card-component > .card-container > .title > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #export-iconId > .icon-color-toolbar-active").click()
    download3 = download3_info.value
    page.locator("a").nth(2).click()
    page.locator("a").filter(has_text="3").click()
    page.locator("div:nth-child(7) > div > esp-grid-container > esp-card-component > .card-container > .card-content > esp-row-dimentional-grid > div > #paginationId > esp-pagination-v2 > .d-flex.w-100 > .pagination-pager > .pagination-first").click()
    page.get_by_text("View 10 row(s)").nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^View 20 row\(s\)$")).nth(1).click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.get_by_role("textbox", name="Filter Value").fill("Promotion")
    page.get_by_label("Column Filter").get_by_role("button", name="Apply").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-cell-filtered > .ag-header-cell-comp-wrapper > .ag-cell-label-container").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button.ag-filter-active > .ag-icon").click()
    page.get_by_label("Column Filter").get_by_role("button", name="Reset").click()
    page.get_by_role("gridcell", name="Promotion-TH PRO BAGEL ROLLBACK 12/29/25 thru 03/29/").dblclick()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
