import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.bbu.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=4&tabIndex=7")
    page.get_by_text("FilterStart Week 01/25/2026").click()
    page.get_by_text("Filter").click()
    page.get_by_text("Start Week / End Week").click()
    page.locator("#Datepick").click()
    page.locator("div").filter(has_text="‹ January 2026 ›").nth(4).click()
    page.get_by_text("4").first.click()
    page.get_by_role("button", name="January").click()
    page.get_by_text("February").first.click()
    page.get_by_role("button", name="2026").first.click()
    page.get_by_role("gridcell", name="2025").click()
    page.get_by_role("button", name="2026").click()
    page.get_by_role("gridcell", name="2024").click()
    page.get_by_role("gridcell", name="January").nth(1).click()
    page.get_by_text("2", exact=True).nth(2).click()
    page.get_by_text("Start Week 01/25/2026 End").click()
    page.get_by_text("Total ByProduct Level None").click()
    page.get_by_text("Total By").click()
    page.get_by_text("Product Level None Location").click()
    page.get_by_text("Product Level").click()
    page.get_by_text("None").first.click()
    page.get_by_text("Select All").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.get_by_text("Brand Level 4").click()
    page.get_by_text("Brand Level 3").click()
    page.get_by_text("Brand Level 2").click()
    page.locator(".overflow-auto > div:nth-child(3)").click()
    page.get_by_text("UPC").click()
    page.get_by_text("Product Level 4").click()
    page.get_by_text("Product Level 3").click()
    page.get_by_text("Product Level 2").click()
    page.get_by_text("Location Level").click()
    page.get_by_text("None").first.click()
    page.get_by_text("Select All").click()
    page.get_by_text("Sales Level 6").click()
    page.get_by_text("Sales Level 5", exact=True).click()
    page.get_by_text("Sales Level 4", exact=True).click()
    page.locator("div:nth-child(8)").click()
    page.get_by_text("Sales Level 1", exact=True).click()
    page.locator(".overflow-auto > div:nth-child(5)").click()
    page.locator("div:nth-child(7)").click()
    page.get_by_text("Depot", exact=True).click()
    page.get_by_text("Sales Level 3", exact=True).click()
    page.get_by_text("BUSS Environment", exact=True).click()
    page.locator("span").filter(has_text="BUSS Route ID").click()
    page.locator("div:nth-child(2) > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("Customer Level").click()
    page.locator("div:nth-child(3) > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("Select All").click()
    page.get_by_text("All").nth(3).click()
    page.get_by_text("Time").click()
    page.get_by_text("None").nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^Weekly$")).nth(3).click()
    page.get_by_text("Measures", exact=True).click()
    page.locator(".measure-filter-list").click()
    page.get_by_text("Measure", exact=True).click()
    page.get_by_text("All Measures").first.click()
    page.get_by_text("Select All Measures").click()
    page.get_by_text("Select All Measures").click()
    page.get_by_text("User Forecast Total").click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32").first.click()
    page.get_by_text("User Forecast Base").click()
    page.locator(".overflow-auto > div:nth-child(3)").click()
    page.locator(".overflow-auto > div:nth-child(5)").click()
    page.get_by_text("Select All Measures").click()
    page.get_by_text("Measure", exact=True).click()
    page.get_by_role("button", name="Download").click()
    page.get_by_text("Please note that a maximum of").click()
    page.get_by_role("button", name="Reset").click()
    page.get_by_role("button", name="Reset").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
