import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.bbu.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=4&tabIndex=4")
    page.get_by_text("Customer Total columns (0)").click()
    page.get_by_text("Customer Total").click()
    page.locator("esp-card-component").filter(has_text="Customer Total columns (0)").get_by_role("button").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("System Forecast")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator(".ag-column-select-column").first.click()
    page.get_by_role("treeitem", name="System Forecast Base (Plan").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator("#ag-839").get_by_text("System Forecast Total (Plan Week)").click()
    page.get_by_label("System Forecast Base (Plan").get_by_text("System Forecast Base (Plan").click()
    page.get_by_label("System Forecast Promotion (").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("System Forecast Total (Plan+1").get_by_text("System Forecast Total (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_label("% Change 6 Week Aged Net").get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_label("6 Week Scan Units Average Column", exact=True).get_by_text("Week Scan Units Average").click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("Freshness (6 Week Average)").get_by_text("Freshness (6 Week Average)").click()
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("esp-card-component").filter(has_text="Customer Total columns (0)").get_by_role("button").click()
    with page.expect_download() as download_info:
        page.locator(".icon-color-toolbar-active.zeb-download-underline").first.click()
    download = download_info.value
    page.locator(".pointer.zeb-adjustments").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Save Preference$")).first.click()
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-body-horizontal-scroll-container").first.click()
    page.get_by_text("Customers columns (0)").click()
    page.get_by_text("Customers").click()
    page.locator("esp-card-component").filter(has_text="Customers columns (0)").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("6")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("treeitem", name="Week Gross Units Average Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="6 Week Aged Net Units Average Column", exact=True).get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="LY 6 Week Aged Net Units").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="% Change 6 Week Aged Net").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_label("Column List 9 Columns").get_by_text("6 Week Scan Units Average", exact=True).click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("6 Week Aged Returns Units").get_by_text("6 Week Aged Returns Units").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator("#ag-989 > .ag-column-panel > .ag-column-select > .ag-column-select-list > .ag-virtual-list-viewport > .ag-virtual-list-container > div > .ag-column-select-column").first.click()
    page.get_by_label("System Forecast Base (Plan Week) Column").get_by_text("System Forecast Base (Plan").click()
    page.get_by_label("System Forecast Promotion (Plan Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("System Forecast Total (Plan+1").get_by_text("System Forecast Total (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("System Forecast Promotion (Plan+1 Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("6 Week Gross Units Average").get_by_text("Week Gross Units Average").click()
    page.get_by_label("6 Week Aged Net Units Average Column", exact=True).get_by_text("6 Week Aged Net Units Average", exact=True).click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_label("% Change 6 Week Aged Net").get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_label("6 Week Scan Units Average Column", exact=True).get_by_text("6 Week Scan Units Average", exact=True).click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("Freshness (6 Week Average)").get_by_text("Freshness (6 Week Average)").click()
    page.get_by_label("6 Week Aged Returns Units").get_by_text("6 Week Aged Returns Units").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    with page.expect_download() as download1_info:
        page.locator("esp-grid-icons-component").filter(has_text="Export").locator("#export-iconId").click()
    download1 = download1_info.value
    page.locator("esp-card-component").filter(has_text="Customers columns (0)").locator("#preference-iconId").click()
    page.locator("div").filter(has_text=re.compile(r"^Reset Preference$")).first.click()
    page.locator(".ag-header-cell.ag-column-first > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-cell-label").click()
    page.locator(".ag-icon.ag-icon-desc").first.click()
    page.locator(".ag-icon.ag-icon-asc").first.click()
    page.get_by_text("3RD PARTY DISTRIB").click()
    page.locator(".ag-group-checkbox").first.click()
    page.locator("esp-row-dimentional-grid span").filter(has_text=re.compile(r"^3RD PARTY DISTRIB$")).click(button="right")
    page.locator("esp-row-dimentional-grid").get_by_text("3RD PARTY DISTRIB").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_text("Contains").click()
    page.get_by_role("option", name="Contains").click()
    page.get_by_text("Contains").click()
    page.get_by_text("Does not contain").click()
    page.get_by_text("Does not contain").click()
    page.get_by_role("option", name="Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_role("option", name="Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_role("option", name="Begins with").click()
    page.get_by_text("Begins with").click()
    page.get_by_role("option", name="Ends with").click()
    page.get_by_text("Ends with").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("AND", exact=True).click()
    page.locator(".ag-labeled.ag-label-align-right.ag-radio-button.ag-input-field.ag-filter-condition-operator.ag-filter-condition-operator-or").click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.get_by_role("button", name="Apply").click()
    page.get_by_text("System Forecast Total (Plan").nth(1).click()
    page.get_by_text("System Forecast Total (Plan").nth(1).click()
    page.get_by_text("System Forecast Total (Plan").nth(1).click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_text("Equals").click()
    page.get_by_role("option", name="Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_role("option", name="Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_role("option", name="Greater than", exact=True).click()
    page.get_by_text("Greater than").click()
    page.get_by_role("option", name="Less than", exact=True).click()
    page.get_by_role("combobox", name="Filtering operator").click()
    page.get_by_text("Less than or equal to").click()
    page.get_by_text("Less than or equal to").click()
    page.get_by_role("option", name="Between").click()
    page.get_by_text("Between").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("AND", exact=True).click()
    page.get_by_text("OR", exact=True).click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.get_by_role("button", name="Apply").click()
    page.locator("esp-row-dimentional-grid #paginationId").click()
    page.get_by_text("Showing 10 out of").click()
    page.get_by_text("Rows per page").click()
    page.get_by_text("View 10 row(s)").first.click()
    page.get_by_text("View 20 row(s)").click()
    page.locator(".dropdown-caret.p-l-16").first.click()
    page.get_by_text("Showing 20 out of 138 1234567Rows per page View 20 row(s) View 10 row(s)View 20").click()
    page.locator(".pagination-next").click()
    page.get_by_text("1234567").click()
    page.locator(".zeb-nav-to-last").click()
    page.get_by_role("listitem").filter(has_text=re.compile(r"^$")).nth(5).click()
    page.locator(".zeb-nav-to-first").click()
    page.get_by_text("FilterTime Latest 13 Next").click()
    page.locator("div").filter(has_text=re.compile(r"^Filter$")).click()
    page.get_by_text("Filter").click()
    page.get_by_text("Time").click()
    page.get_by_text("Latest 13 Next").first.click()
    page.get_by_text("Latest 5 Next 4").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 5 Next 12$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 13 Next 4$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.get_by_text("Latest 13 Next 12").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 26 Next 4$")).nth(1).click()
    page.get_by_text("Weekly Summary Customer:3RD").click()
    page.get_by_text("Weekly Summary").click()
    page.get_by_text("Customer:3RD PARTY DISTRIB").first.click()
    page.get_by_text("Customer", exact=True).nth(2).click()
    page.get_by_text("3RD PARTY DISTRIB").nth(1).click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("All").nth(4).click()
    page.get_by_text("All").nth(4).click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.get_by_text("User Override Total").nth(1).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("User Override Promotion").nth(1).click()
    page.get_by_text("System Forecast Total").nth(5).click()
    page.get_by_text("System Forecast Base").nth(3).click()
    page.get_by_text("System Forecast Promotion").nth(3).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("Weekly Forecast Promotion", exact=True).click()
    page.get_by_text("Daily Suggested Order Total").nth(1).click()
    page.get_by_text("Daily Suggested Order Base", exact=True).click()
    page.locator(".overflow-auto > div:nth-child(18)").click()
    page.get_by_text("Gross Units").nth(2).click()
    page.get_by_text("Raw Forecast").nth(1).click()
    page.get_by_text("Daily Suggested Order Promotion", exact=True).click()
    page.get_by_text("% Change Aged Net Units", exact=True).click()
    page.get_by_text("Aged Net Units LY", exact=True).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("Scan Units LY", exact=True).click()
    page.get_by_text("Scan Units LY", exact=True).click()
    page.get_by_text("Scan Units LY", exact=True).click()
    page.get_by_text("Freshness").nth(2).click()
    page.get_by_text("% Change Scan Units", exact=True).click()
    page.get_by_text("Aged Return Units").nth(1).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("System MAPE", exact=True).click()
    page.get_by_text("Forecast Value Add - MAPE", exact=True).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("System Bias", exact=True).click()
    page.get_by_text("Forecast Value Add - Bias", exact=True).click()
    page.get_by_text("Promo", exact=True).nth(1).click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.locator("esp-card-component").filter(has_text="Weekly Summary Customer:3RD").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("2025-07-27")
    page.get_by_text("-07-27 (31)").click()
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_label("-07-27 (31) Column").get_by_text("-07-27 (31)").click()
    page.get_by_label("-08-03 (32) Column").get_by_text("-08-03 (32)").click()
    page.get_by_label("-08-10 (33) Column").get_by_text("-08-10 (33)").click()
    page.get_by_label("-08-24 (35) Column").get_by_text("-08-24 (35)").click()
    page.get_by_text("-08-24 (35)").click()
    page.get_by_text("-10-19 (43)").click()
    page.locator("esp-card-component").filter(has_text="Weekly Summary Customer:3RD").get_by_role("button").click()
    with page.expect_download() as download2_info:
        page.locator("esp-grid-icons-component").filter(has_text="Export").locator("#export-iconId").click()
    download2 = download2_info.value
    page.locator("div:nth-child(4) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("div").filter(has_text=re.compile(r"^Save Preference$")).first.click()
    page.locator("div:nth-child(4) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-header-cell.ag-column-first.ag-header-parent-hidden.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-cell-label").click()
    page.locator("esp-column-dimentional-grid").get_by_text("User Forecast Total").click()
    page.locator("i").first.click()
    page.locator("i").nth(2).click()
    page.locator("span").filter(has_text="User Override Total").first.click()
    page.get_by_text("System Forecast Total", exact=True).click()
    page.locator("i").nth(4).click()
    page.locator("span").filter(has_text="Weekly Forecast Total").first.click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator("span").filter(has_text="Daily Suggested Order Total").first.click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-expanded > .zeb-chevron-down").click()
    page.locator(".ag-row-odd.ag-row-no-focus.ag-row-not-inline-editing.ag-row.ag-row-level-0.ag-row-group.ag-row-group-contracted.ag-row-position-absolute.ag-row-hover > .ag-cell-value > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator("esp-column-dimentional-grid").get_by_text("Aged Net Units", exact=True).click()
    page.locator("esp-column-dimentional-grid").get_by_text("Scan Units").click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator(".ag-row-odd.ag-row-no-focus.ag-row-not-inline-editing.ag-row.ag-row-level-0.ag-row-group.ag-row-group-contracted.ag-row-position-absolute.ag-row-hover > .ag-cell-value > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator("esp-column-dimentional-grid").get_by_text("User MAPE").click()
    page.get_by_text("Weekly Trend Customer:3RD").click()
    page.get_by_text("Weekly Trend").click()
    page.locator("dp-line-bar-chart").get_by_text("Customer:3RD PARTY DISTRIB").click()
    page.locator("dp-line-bar-chart").get_by_text("Customer:3RD PARTY DISTRIB").click()
    page.locator("dp-line-bar-chart").get_by_text("Customer", exact=True).click()
    page.locator("dp-line-bar-chart").get_by_text("3RD PARTY DISTRIB").click()
    page.get_by_text("User Forecast Total, User").first.click()
    page.locator("dp-line-bar-chart span").filter(has_text="User Forecast Total").click()
    page.get_by_text("User Forecast Base").click()
    page.locator(".overflow-auto > div:nth-child(3)").click()
    page.locator("dp-line-bar-chart span").filter(has_text="User Override Total").click()
    page.get_by_text("User Override Base").click()
    page.get_by_text("User Override Promotion").click()
    page.locator(".overflow-auto > div:nth-child(6)").click()
    page.locator("dp-line-bar-chart").get_by_text("System Forecast Total").click()
    page.get_by_text("System Forecast Base", exact=True).click()
    page.get_by_text("System Forecast Promotion", exact=True).click()
    page.locator(".overflow-auto > div:nth-child(10)").click()
    page.locator("dp-line-bar-chart").get_by_text("Weekly Forecast Base").click()
    page.locator("dp-line-bar-chart").get_by_text("Weekly Forecast Promotion").click()
    page.locator("dp-line-bar-chart").get_by_text("Weekly Forecast Promotion").click()
    page.locator(".overflow-auto > div:nth-child(15)").click()
    page.locator(".overflow-auto > div:nth-child(14)").click()
    page.locator("dp-line-bar-chart").get_by_text("Daily Suggested Order Total").click()
    page.locator("span").filter(has_text="Daily Suggested Order Promotion").click()
    page.locator("span").filter(has_text="Daily Suggested Order Base").click()
    page.locator("span").filter(has_text="Daily Suggested Order Base").click()
    page.get_by_text("Aged Net Units", exact=True).nth(1).click()
    page.locator(".overflow-auto > div:nth-child(15)").click()
    page.locator(".overflow-auto > div:nth-child(15)").click()
    page.locator(".overflow-auto > div:nth-child(17)").click()
    page.locator("dp-line-bar-chart").get_by_text("Aged Net Units", exact=True).click()
    page.locator("dp-line-bar-chart").get_by_text("Aged Net Units LY").click()
    page.locator("dp-line-bar-chart").get_by_text("Scan Units LY").click()
    page.locator(".overflow-auto > div:nth-child(22)").click()
    page.locator(".overflow-auto > div:nth-child(23)").click()
    page.locator(".overflow-auto > div:nth-child(24)").click()
    page.locator("dp-line-bar-chart").get_by_text("Forecast Value Add - MAPE").click()
    page.locator("div:nth-child(26)").click()
    page.locator("div:nth-child(27)").click()
    page.locator("dp-line-bar-chart").get_by_text("Forecast Value Add - Bias").click()
    page.get_by_text("User Forecast Base, User").first.click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("div").filter(has_text=re.compile(r"^Reset Preference$")).first.click()
    page.locator("path:nth-child(157)").click()
    page.locator("svg").get_by_text("User Forecast Total").click()
    page.locator("svg").get_by_text("User Override Total").click()
    page.locator("text").filter(has_text="Aged Net Units").click()
    page.locator("svg").click()
    page.get_by_text("0%", exact=True).click()
    page.get_by_text("20%").click()
    page.get_by_text("02/01/").click()
    page.get_by_text("01/11/").click()
    page.get_by_text("12/21/").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
