import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.bbu.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=4&tabIndex=5")
    page.get_by_text("Customer Total columns (0)").click()
    page.get_by_text("Customer Total").click()
    page.locator("esp-card-component").filter(has_text="Customer Total columns (0)").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("System")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator(".ag-column-select-column").first.click()
    page.get_by_role("treeitem", name="System Forecast Base (Plan").get_by_label("Press SPACE to toggle").check()
    page.locator("div:nth-child(3) > .ag-column-select-column").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_label("System Forecast Promotion (").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("System Forecast Total (Plan+1").get_by_text("System Forecast Total (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("System Forecast Promotion (").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("6 Week Gross Units Average").get_by_text("Week Gross Units Average").click()
    page.get_by_label("6 Week Aged Net Units Average Column", exact=True).get_by_text("Week Aged Net Units Average").click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_label("% Change 6 Week Aged Net").get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_label("6 Week Scan Units Average Column", exact=True).get_by_text("Week Scan Units Average").click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("Freshness (6 Week Average)").get_by_text("Freshness (6 Week Average)").click()
    page.get_by_label("6 Week Aged Returns Units").get_by_text("6 Week Aged Returns Units").click()
    page.locator("#ag-169").get_by_text("System Forecast Total (Plan Week)").click()
    page.get_by_label("System Forecast Base (Plan").get_by_text("System Forecast Base (Plan").click()
    page.locator("esp-card-component").filter(has_text="Customer Total columns (0)").get_by_role("button").click()
    with page.expect_download() as download_info:
        page.locator("esp-grid-icons-component").filter(has_text="Export").locator("#export-iconId").click()
    download = download_info.value
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Save Preference").click()
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-body-horizontal-scroll-container").first.click()
    page.get_by_text("Customers columns (0)").click()
    page.get_by_text("Customers").click()
    page.get_by_text("Customers columns (0)").click()
    page.locator("esp-card-component").filter(has_text="Customers columns (0)").get_by_role("button").click()
    page.locator("#ag-87 > .ag-column-panel > .ag-column-select > .ag-column-select-header").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("Fresh")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator("#ag-87").get_by_text("System Forecast Total (Plan Week)").click()
    page.get_by_label("System Forecast Base (Plan Week) Column").get_by_text("System Forecast Base (Plan").click()
    page.get_by_label("System Forecast Promotion (Plan Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("System Forecast Total (Plan+1").get_by_text("System Forecast Total (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("System Forecast Promotion (Plan+1 Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("6 Week Gross Units Average").get_by_text("Week Gross Units Average").click()
    page.get_by_label("6 Week Aged Net Units Average Column", exact=True).get_by_text("6 Week Aged Net Units Average", exact=True).click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_label("% Change 6 Week Aged Net").get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("6 Week Scan Units Average Column", exact=True).get_by_text("Week Scan Units Average").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("Freshness (6 Week Average)").get_by_text("Freshness (6 Week Average)").click()
    page.get_by_label("6 Week Aged Returns Units").get_by_text("6 Week Aged Returns Units").click()
    page.locator("esp-card-component").filter(has_text="Customers columns (0)").get_by_role("button").click()
    with page.expect_download() as download1_info:
        page.locator("div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download1 = download1_info.value
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator("esp-row-dimentional-grid").get_by_text("Customer").click()
    page.locator(".ag-icon.ag-icon-desc").first.click()
    page.locator(".ag-icon.ag-icon-desc").first.click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_text("Contains").click()
    page.get_by_label("Select Field").get_by_text("Contains").click()
    page.get_by_text("Contains").click()
    page.get_by_text("Does not contain").click()
    page.get_by_text("Does not contain").click()
    page.get_by_role("option", name="Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_role("option", name="Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_role("option", name="Begins with").click()
    page.get_by_role("combobox", name="Filtering operator").click()
    page.get_by_role("option", name="Ends with").click()
    page.get_by_text("Ends with").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("Blank").click()
    page.get_by_role("option", name="Not blank").click()
    page.get_by_text("AND", exact=True).click()
    page.get_by_text("OR", exact=True).click()
    page.get_by_text("Contains").click()
    page.get_by_label("Column Filter").get_by_text("Contains").click()
    page.get_by_role("textbox", name="Filter Value").click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.get_by_role("button", name="Apply").click()
    page.locator("span").filter(has_text="3RD PARTY DISTRIB").first.click()
    page.get_by_text("3RD PARTY DISTRIB").click()
    page.locator(".ag-group-checkbox").first.click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  99 CENT").get_by_label("Press Space to toggle row").check()
    page.get_by_text("System Forecast Total (Plan").nth(2).click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-desc > .ag-header-icon > .ag-icon").click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_text("Equals").click()
    page.get_by_label("Select Field").get_by_text("Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_text("Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_text("Greater than", exact=True).click()
    page.get_by_text("Greater than").click()
    page.get_by_text("Greater than or equal to").click()
    page.get_by_text("Greater than or equal to").click()
    page.get_by_role("option", name="Less than", exact=True).click()
    page.get_by_text("Less than").click()
    page.get_by_text("Less than or equal to").click()
    page.get_by_text("Less than or equal to").click()
    page.get_by_role("option", name="Between").click()
    page.get_by_text("Between").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("Blank").click()
    page.get_by_role("option", name="Not blank").click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-desc > .ag-header-icon > .ag-icon").click()
    page.get_by_role("button", name="Apply").click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-desc > .ag-header-cell-label > .ag-sort-indicator-container > .ag-sort-indicator-icon.ag-sort-descending-icon > .ag-icon").click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-asc > .ag-header-cell-label > .ag-sort-indicator-container > .ag-sort-indicator-icon.ag-sort-ascending-icon > .ag-icon").click()
    page.get_by_text("System Forecast Base (Plan Week)").click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-desc > .ag-header-cell-label > .ag-sort-indicator-container > .ag-sort-indicator-icon.ag-sort-descending-icon > .ag-icon").click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-desc > .ag-header-cell-label > .ag-sort-indicator-container > .ag-sort-indicator-icon.ag-sort-descending-icon > .ag-icon").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button.ag-has-popup-positioned-under > .ag-icon").click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_role("combobox", name="Filtering operator").click()
    page.get_by_label("Select Field").get_by_text("Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_text("Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_role("option", name="Greater than", exact=True).click()
    page.get_by_text("Greater than").click()
    page.get_by_role("option", name="Less than", exact=True).click()
    page.get_by_text("Less than").click()
    page.get_by_text("Greater than or equal to").click()
    page.get_by_text("Greater than or equal to").click()
    page.get_by_role("option", name="Less than or equal to").click()
    page.get_by_text("Less than or equal to").click()
    page.get_by_role("option", name="Between").click()
    page.get_by_text("Between").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("Blank").click()
    page.get_by_role("option", name="Not blank").click()
    page.locator(".ag-labeled.ag-label-align-right.ag-radio-button").first.click()
    page.locator(".ag-labeled.ag-label-align-right.ag-radio-button.ag-input-field.ag-filter-condition-operator.ag-filter-condition-operator-or").click()
    page.get_by_role("spinbutton", name="Filter Value").click()
    page.get_by_role("spinbutton", name="Filter Value").fill("2")
    page.get_by_role("spinbutton", name="Filter Value").press("Enter")
    page.get_by_role("spinbutton", name="Filter Value").click()
    page.get_by_role("button", name="Apply").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button.ag-filter-active > .ag-icon").click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_text("Customers columns (0)").click()
    page.locator("esp-row-dimentional-grid #paginationId").click()
    page.get_by_text("Showing 10 out of").click()
    page.get_by_text("Showing 10 out of 138 12345").click()
    page.get_by_text("View 10 row(s)").first.click()
    page.locator("span").filter(has_text=re.compile(r"^View 10 row\(s\)$")).click()
    page.get_by_text("Rows per page").click()
    page.get_by_text("Showing 10 out of 138 12345").click()
    page.get_by_role("listitem").filter(has_text=re.compile(r"^1$")).click()
    page.locator("a").filter(has_text="2").click()
    page.locator(".zeb-chevron-left").click()
    page.get_by_text("12345...14").click()
    page.get_by_text("12345...14").click()
    page.locator(".pagination-next > .zeb-chevron-right").click()
    page.locator(".zeb-nav-to-last").click()
    page.locator(".w-100.p-h-16").click()
    page.locator("div").filter(has_text=re.compile(r"^View 20 row\(s\)$")).first.click()
    page.get_by_text("Showing 20 out of").click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  3RD PARTY DISTRIB").get_by_label("Press Space to toggle row").check()
    page.get_by_text("FilterTime Latest Order &").click()
    page.locator("div").filter(has_text=re.compile(r"^Filter$")).click()
    page.get_by_text("Time").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white").click()
    page.locator("span").filter(has_text="Latest Order & Plan Week").click()
    page.get_by_text("FilterTime Latest Order &").click()
    page.get_by_text("Daily Summary Customer:3RD").click()
    page.get_by_text("Daily Summary").click()
    page.get_by_text("Customer", exact=True).nth(2).click()
    page.get_by_text("Customer:3RD PARTY DISTRIB").first.click()
    page.get_by_text("3RD PARTY DISTRIB").nth(1).click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("Aged Net Units (CW-5)", exact=True).click()
    page.get_by_text("Aged Net Units (CW-6)", exact=True).click()
    page.get_by_text("Scan Units (CW-4)", exact=True).click()
    page.get_by_text("Scan Units (CW-3)").nth(1).click()
    page.get_by_text("Scan Units (CW-5)", exact=True).click()
    page.locator("span").filter(has_text="Scan Units (CW-6)").click()
    page.get_by_text("Daily Summary Customer:3RD").click()
    page.locator("esp-card-component").filter(has_text="Daily Summary Customer:3RD").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_label("/01(Sun) Column").get_by_text("/01(Sun)").click()
    page.get_by_label("/02(Mon) Column").get_by_text("/02(Mon)").click()
    page.get_by_role("treeitem", name="/03(Tue) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="/05(Thu) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="/04(Wed) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    with page.expect_download() as download2_info:
        page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download2 = download2_info.value
    page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("esp-card-component").filter(has_text="Daily Summary Customer:3RD").get_by_role("button").click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("Select All").click()
    page.get_by_text("Daily Summary Customer:3RD").click()
    page.locator(".ag-header-cell.ag-column-first.ag-header-parent-hidden.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-cell-label").click()
    page.get_by_text("User Suggested Order Total").click()
    page.locator("i").first.click()
    page.get_by_text("User Override Total").click()
    page.locator("i").nth(2).click()
    page.locator("esp-column-dimentional-grid").get_by_text("Gross Units (CW-3)").click()
    page.locator("span").filter(has_text="Gross Units (CW-3)").first.click()
    page.locator("i").nth(5).click()
    page.locator("esp-column-dimentional-grid").get_by_text("Aged Net Units (CW-3)").click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator(".ag-row-no-focus.ag-row-not-inline-editing.ag-row.ag-row-level-0.ag-row-group.ag-row-group-contracted.ag-row-position-absolute.ag-row-even.ag-row-hover > .ag-cell-value > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator("esp-column-dimentional-grid").get_by_text("Scan Units (CW-3)").click()
    page.get_by_text("Daily Trend Customer:3RD").click()
    page.locator("svg").click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .p-l-40").click()
    page.locator("dp-line-bar-chart").get_by_text("Customer", exact=True).click()
    page.locator("dp-line-bar-chart").get_by_text("Customer:3RD PARTY DISTRIB").click()
    page.locator("path:nth-child(79)").click()
    page.get_by_text("User Suggested Order Base,").first.click()
    page.locator("span").filter(has_text="User Suggested Order Base").click()
    page.locator("span").filter(has_text="User Suggested Order Promotion").click()
    page.locator("span").filter(has_text="User Override Base").click()
    page.locator("span").filter(has_text="User Override Promotion").click()
    page.locator("dp-line-bar-chart span").filter(has_text="Gross Units (CW-3)").click()
    page.locator("dp-line-bar-chart").get_by_text("Gross Units (CW-4)").click()
    page.locator(".overflow-auto > div:nth-child(7)").click()
    page.locator("div:nth-child(8) > .d-flex").click()
    page.locator(".overflow-auto > div:nth-child(9)").click()
    page.locator("div:nth-child(10) > .d-flex").click()
    page.locator("dp-line-bar-chart").get_by_text("Aged Net Units (CW-5)").click()
    page.locator("dp-line-bar-chart").get_by_text("Aged Net Units (CW-6)").click()
    page.locator("dp-line-bar-chart span").filter(has_text="Scan Units (CW-3)").click()
    page.locator("dp-line-bar-chart").get_by_text("Scan Units (CW-4)").click()
    page.locator(".overflow-auto > div:nth-child(15)").click()
    page.locator("dp-line-bar-chart").get_by_text("Scan Units (CW-6)").click()
    page.locator(".ellipses > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("Daily Trend Customer:3RD").click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator("svg").click()
    page.locator("svg").get_by_text("02/01/").click()
    page.get_by_text("02/02/").click()
    page.get_by_text("02/03/").click()
    page.locator("svg").click()
    page.locator("path:nth-child(67)").click()
    page.get_by_text("User Override Promotion", exact=True).click()
    page.get_by_text("User Override Base", exact=True).click()
    page.locator("path:nth-child(79)").click()
    page.locator("path:nth-child(96)").click()
    page.locator("path:nth-child(102)").click()
    page.locator("svg").click()
    page.locator("path:nth-child(102)").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
