import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.bbu.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=4&tabIndex=2")
    page.locator("esp-card-component").filter(has_text="Product Total columns (0)").get_by_role("button").click()
    page.get_by_role("treeitem", name="System Forecast Total (Plan Week) Column").get_by_label("Press SPACE to toggle").uncheck()
    page.get_by_role("treeitem", name="System Forecast Base (Plan").get_by_label("Press SPACE to toggle").uncheck()
    page.get_by_role("treeitem", name="System Forecast Promotion (").get_by_label("Press SPACE to toggle").uncheck()
    page.locator("div:nth-child(3) > .ag-column-select-column").click()
    page.get_by_role("treeitem", name="System Forecast Promotion (").get_by_label("Press SPACE to toggle").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator(".pointer.zeb-adjustments").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Save Preference$")).nth(1).click()
    with page.expect_download() as download_info:
        page.locator(".icon-color-toolbar-active.zeb-download-underline").first.click()
    download = download_info.value
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Reset Preference").click()
    page.get_by_text("Products").click()
    page.locator("esp-card-component").filter(has_text="Products columns (0)").get_by_role("button").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="System Forecast Total (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="System Forecast Base (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="System Forecast Promotion (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="System Forecast Total (Plan+1").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="System Forecast Base (Plan+1").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="System Forecast Promotion (Plan+1 Week) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Week Gross Units Average Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="6 Week Aged Net Units Average Column", exact=True).get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("div").filter(has_text=re.compile(r"^Save Preference$")).nth(1).click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.get_by_role("textbox", name="Filter Value").fill("BARCEL")
    page.get_by_role("button", name="Apply").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.get_by_role("button", name="Reset").click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  ARNOLD-BRWNBRY-OROWT").get_by_label("Press Space to toggle row").check()
    page.locator("a").filter(has_text="2").click()
    page.locator("a").filter(has_text="3").click()
    page.get_by_role("listitem").filter(has_text=re.compile(r"^$")).nth(4).click()
    page.locator(".dropdown-caret.p-l-16").first.click()
    page.locator("div").filter(has_text=re.compile(r"^View 20 row\(s\)$")).nth(1).click()
    page.get_by_text("Filter").click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 5 Next 4$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 5 Next 12$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 13 Next 4$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 13 Next 12$")).nth(1).click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".overflow-auto > div:nth-child(2) > .d-flex").click()
    page.locator(".overflow-auto > div:nth-child(3) > .d-flex").click()
    page.locator(".overflow-auto > div:nth-child(4)").click()
    page.locator(".overflow-auto > div:nth-child(5)").click()
    page.locator(".overflow-auto > div:nth-child(6)").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("esp-card-component").filter(has_text="Weekly Summary Product:ARNOLD").get_by_role("button").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="-10-26 (44) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="-11-02 (45) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="-11-09 (46) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="-11-16 (47) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("esp-card-component").filter(has_text="Weekly Summary Product:ARNOLD").get_by_role("button").click()
    page.locator("div:nth-child(4) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    with page.expect_download() as download1_info:
        page.locator("div:nth-child(3) > #export-iconId > .icon-color-toolbar-active").click()
    download1 = download1_info.value
    page.locator("div:nth-child(4) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.get_by_text("-02-15 (08)").click()
    page.get_by_role("img").nth(5).click()
    page.locator("esp-card-component").filter(has_text="Event Details columns (0)").get_by_role("button").click()
    page.get_by_role("treeitem", name="Event Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="UPC 12 Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="Customer Level 2 Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="Start Date Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="End Date Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator(".col-12.m-t-16 > div > esp-grid-container > esp-card-component > .card-container > .title > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div:nth-child(2) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    with page.expect_download() as download2_info:
        page.locator("div:nth-child(6) > div > esp-grid-container > esp-card-component > .card-container > .title > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #export-iconId > .icon-color-toolbar-active").click()
    download2 = download2_info.value
    page.locator(".col-12.m-t-16 > div > esp-grid-container > esp-card-component > .card-container > .title > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div:nth-child(2) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.get_by_role("textbox", name="Filter Value").fill("Scan Track")
    page.get_by_role("button", name="Apply").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button.ag-filter-active > .ag-icon").click()
    page.get_by_role("button", name="Reset").click()
    page.get_by_text("Products").click()
    page.locator("span").filter(has_text="ARNOLD-BRWNBRY-OROWT").first.dblclick()
    page.locator("span").filter(has_text="ABO COUNTRY").first.dblclick()
    page.locator("span").filter(has_text="ABO COUNTRY").first.click()
    page.get_by_text("ABO COUNTRY").nth(1).dblclick()
    page.locator("span").filter(has_text=re.compile(r"^OR CTY BTRMK WP 24Z-731300012500$")).click(button="right")
    page.get_by_text("Drill up").click()
    page.locator("span").filter(has_text="ABO COUNTRY").first.click(button="right")
    page.get_by_text("Drill up").click()
    page.locator("span").filter(has_text="ABO COUNTRY").first.click(button="right")
    page.get_by_text("Drill up").click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  ARNOLD-BRWNBRY-OROWT").get_by_label("Press Space to toggle row").check()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
