import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.bbu.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=4&tabIndex=3")
    page.get_by_text("Product Total columns (0)").click()
    page.get_by_text("Product Total columns (0)").click()
    page.get_by_text("Product Total").click()
    page.locator("esp-card-component").filter(has_text="Product Total columns (0)").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("system")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator(".ag-column-select-column").first.click()
    page.get_by_role("treeitem", name="System Forecast Base (Plan").get_by_label("Press SPACE to toggle").uncheck()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("treeitem", name="System Forecast Total (Plan Week) Column").click()
    page.get_by_role("treeitem", name="System Forecast Base (Plan").get_by_label("Press SPACE to toggle").uncheck()
    page.get_by_label("System Forecast Promotion (").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("System Forecast Total (Plan+1").get_by_text("System Forecast Total (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("System Forecast Promotion (Plan+1 Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("6 Week Gross Units Average").get_by_text("Week Gross Units Average").click()
    page.get_by_label("6 Week Aged Net Units Average Column", exact=True).get_by_text("Week Aged Net Units Average").click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("6 Week Scan Units Average Column", exact=True).get_by_text("Week Scan Units Average").click()
    page.get_by_label("% Change 6 Week Aged Net").get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("Freshness (6 Week Average)").get_by_text("Freshness (6 Week Average)").click()
    page.get_by_label("6 Week Aged Returns Units").get_by_text("6 Week Aged Returns Units").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("esp-card-component").filter(has_text="Product Total columns (0)").get_by_role("button").click()
    with page.expect_download() as download_info:
        page.locator(".icon-color-toolbar-active.zeb-download-underline").first.click()
    download = download_info.value
    page.get_by_text("Please note that a maximum of").click()
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Save Preference").click()
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-body-horizontal-scroll-container").first.click()
    page.get_by_text("Products columns (0) TopBottom").click()
    page.get_by_text("Products").click()
    page.locator("esp-card-component").filter(has_text="Products columns (0)").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("6")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("treeitem", name="Week Gross Units Average Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_label("Column List 9 Columns").get_by_text("6 Week Aged Net Units Average", exact=True).click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("#ag-87 > .ag-column-panel > .ag-column-select > .ag-column-select-list > .ag-virtual-list-viewport > .ag-virtual-list-container > div > .ag-column-select-column").first.click()
    page.get_by_role("treeitem", name="System Forecast Base (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="System Forecast Promotion (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="System Forecast Total (Plan+1").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="System Forecast Base (Plan+1").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="System Forecast Promotion (Plan+1 Week) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.locator("div:nth-child(7) > .ag-column-select-column").click()
    page.get_by_role("treeitem", name="6 Week Aged Net Units Average Column", exact=True).get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="LY 6 Week Aged Net Units").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.locator("div:nth-child(11) > .ag-column-select-column").click()
    page.get_by_role("treeitem", name="% Change 6 Week Aged Net").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="LY 6 Week Scan Units Average").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="% Change 6 Week Scan Units").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.locator("div:nth-child(14) > .ag-column-select-column").click()
    page.locator("div:nth-child(15) > .ag-column-select-column").uncheck()
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.locator("esp-card-component").filter(has_text="Products columns (0)").get_by_role("button").click()
    with page.expect_download() as download1_info:
        page.locator("div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download1 = download1_info.value
    page.get_by_text("Please note that a maximum of").click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator(".ag-header-cell.ag-column-first.ag-header-parent-hidden.ag-header-cell-sortable > .ag-header-cell-comp-wrapper > .ag-cell-label-container").click()
    page.locator("esp-row-dimentional-grid").get_by_text("Product").click()
    page.get_by_text("Product 1").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_role("combobox", name="Filtering operator").click()
    page.get_by_role("option", name="Contains").click()
    page.get_by_text("Contains").click()
    page.get_by_text("Does not contain").click()
    page.get_by_role("combobox", name="Filtering operator").click()
    page.get_by_role("option", name="Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_text("Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_role("option", name="Begins with").click()
    page.get_by_text("Begins with").click()
    page.get_by_role("option", name="Ends with").click()
    page.get_by_text("Ends with").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("AND", exact=True).click()
    page.get_by_text("OR", exact=True).click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_role("button", name="Reset").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button > .ag-icon").first.click()
    page.get_by_role("button", name="Apply").click()
    page.locator("span").filter(has_text="ARNOLD-BRWNBRY-OROWT").first.click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  ARNOLD-BRWNBRY-OROWT").get_by_label("Press Space to toggle row").check()
    page.locator("esp-row-dimentional-grid span").filter(has_text=re.compile(r"^ARNOLD-BRWNBRY-OROWT$")).click(button="right")
    page.locator("esp-row-dimentional-grid").get_by_text("ARNOLD-BRWNBRY-OROWT").click()
    page.locator("esp-row-dimentional-grid").get_by_text("ARNOLD-BRWNBRY-OROWT").click()
    page.locator("span").filter(has_text=re.compile(r"^ARTESANO$")).click()
    page.get_by_text("ARTESANO").click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  ARTESANO").get_by_label("Press Space to toggle row").check()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-checkbox").dblclick()
    page.get_by_text("System Forecast Total (Plan").nth(3).click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-desc > .ag-header-cell-label > .ag-sort-indicator-container > .ag-sort-indicator-icon.ag-sort-descending-icon > .ag-icon").click()
    page.locator(".ag-cell-label-container.ag-header-cell-sorted-asc > .ag-header-cell-label > .ag-sort-indicator-container > .ag-sort-indicator-icon.ag-sort-ascending-icon > .ag-icon").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .ag-icon").click()
    page.locator(".ag-filter-body-wrapper").click()
    page.get_by_role("combobox", name="Filtering operator").click()
    page.get_by_role("option", name="Equals").click()
    page.get_by_text("Equals").click()
    page.get_by_role("option", name="Does not equal").click()
    page.get_by_text("Does not equal").click()
    page.get_by_role("option", name="Greater than", exact=True).click()
    page.get_by_text("Greater than").click()
    page.get_by_text("Greater than or equal to").click()
    page.get_by_text("Greater than or equal to").click()
    page.get_by_role("option", name="Less than", exact=True).click()
    page.get_by_text("Less than").click()
    page.get_by_role("option", name="Between").click()
    page.get_by_text("Between").click()
    page.get_by_role("option", name="Blank", exact=True).click()
    page.get_by_text("AND", exact=True).click()
    page.get_by_text("OR", exact=True).click()
    page.get_by_role("spinbutton", name="Filter Value").click()
    page.get_by_role("spinbutton", name="Filter Value").fill("1")
    page.get_by_role("spinbutton", name="Filter Value").click()
    page.get_by_role("button", name="Apply").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-cell-filtered > .ag-header-cell-comp-wrapper > .ag-cell-label-container").click()
    page.locator(".ag-header-icon.ag-header-cell-filter-button.ag-filter-active > .ag-icon").click()
    page.get_by_role("button", name="Clear").click()
    page.get_by_role("button", name="Reset").click()
    page.locator("esp-card-component").filter(has_text="Products columns (0)").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("treeitem", name="System Forecast Total (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="System Forecast Base (Plan Week) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_label("System Forecast Promotion (Plan Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("System Forecast Total (Plan+1").get_by_text("System Forecast Total (Plan+1").click()
    page.get_by_label("System Forecast Base (Plan+1").get_by_text("System Forecast Base (Plan+1").click()
    page.get_by_label("System Forecast Promotion (Plan+1 Week) Column").get_by_text("System Forecast Promotion (").click()
    page.get_by_label("6 Week Gross Units Average").get_by_text("Week Gross Units Average").click()
    page.get_by_label("LY 6 Week Aged Net Units").get_by_text("LY 6 Week Aged Net Units").click()
    page.get_by_label("6 Week Aged Net Units Average Column", exact=True).get_by_text("Week Aged Net Units Average").click()
    page.get_by_label("6 Week Aged Net Units Average Column", exact=True).get_by_text("Week Aged Net Units Average").click()
    page.get_by_label("% Change 6 Week Aged Net").get_by_text("% Change 6 Week Aged Net").click()
    page.get_by_label("% Change 6 Week Scan Units").get_by_text("% Change 6 Week Scan Units").click()
    page.get_by_label("6 Week Aged Returns Units").get_by_text("6 Week Aged Returns Units").click()
    page.get_by_label("Freshness (6 Week Average)").get_by_text("Freshness (6 Week Average)").click()
    page.get_by_label("LY 6 Week Scan Units Average").get_by_text("LY 6 Week Scan Units Average").click()
    page.get_by_label("6 Week Scan Units Average Column", exact=True).get_by_text("Week Scan Units Average").click()
    page.locator("esp-card-component").filter(has_text="Products columns (0)").get_by_role("button").click()
    with page.expect_download() as download2_info:
        page.locator("div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download2 = download2_info.value
    page.get_by_text("Please note that a maximum of").click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.get_by_text("Showing 10 out of 28 123Rows").click()
    page.get_by_text("Rows per page View 10 row(s)").click()
    page.locator("span").filter(has_text=re.compile(r"^View 10 row\(s\)$")).click()
    page.get_by_text("Showing 10 out of").click()
    page.get_by_text("View 10 row(s)").first.click()
    page.locator("div").filter(has_text=re.compile(r"^View 20 row\(s\)$")).first.click()
    page.get_by_text("Showing 20 out of").click()
    page.get_by_text("12", exact=True).click()
    page.locator("a").filter(has_text="2").click()
    page.locator(".zeb-chevron-left").click()
    page.get_by_text("12", exact=True).click()
    page.get_by_text("12", exact=True).click()
    page.locator(".pagination-last").click()
    page.locator(".zeb-nav-to-first").click()
    page.get_by_role("row", name="Press Space to toggle row selection (unchecked)  THOMAS BRANDS").get_by_label("Press Space to toggle row").check()
    page.locator(".card-content.p-24").click()
    page.get_by_text("FilterTime Latest Order &").click()
    page.locator("div").filter(has_text=re.compile(r"^Filter$")).click()
    page.get_by_text("Time").click()
    page.get_by_text("Latest Order & Plan Week").first.click()
    page.get_by_text("Daily Summary Product:THOMAS").click()
    page.get_by_text("Daily Summary").click()
    page.get_by_text("Product:THOMAS BRANDS").first.click()
    page.get_by_text("Product", exact=True).nth(2).click()
    page.get_by_text("THOMAS BRANDS").nth(1).click()
    page.get_by_text("Daily Summary Product:THOMAS").click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.get_by_text("User Suggested Order Total").first.click()
    page.get_by_text("User Suggested Order Base").nth(1).click()
    page.get_by_text("User Suggested Order Promotion").nth(1).click()
    page.get_by_text("User Override Total").nth(1).click()
    page.get_by_text("User Override Base").nth(1).click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.get_by_text("ION Suggested Order Promotion").nth(1).click()
    page.get_by_text("Gross Units (CW-4)", exact=True).click()
    page.get_by_text("Gross Units (CW-3)").nth(1).click()
    page.get_by_text("Aged Net Units (CW-3)").nth(1).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.get_by_text("Aged Net Units (CW-6)", exact=True).click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32.p-r-16.selected").first.click()
    page.get_by_text("Scan Units (CW-4)", exact=True).click()
    page.get_by_text("Scan Units (CW-4)", exact=True).click()
    page.locator(".overflow-auto > div:nth-child(21)").click()
    page.locator("div:nth-child(20) > .d-flex").click()
    page.get_by_text("Scan Units (CW-4)").first.click()
    page.get_by_text("Scan Units (CW-4)").first.click()
    page.get_by_text("Select All").click()
    page.get_by_text("All").nth(4).click()
    page.locator("esp-card-component").filter(has_text="Daily Summary Product:THOMAS").get_by_role("button").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("02/1")
    page.locator("#ag-4958 > .ag-column-panel > .ag-column-select > .ag-column-select-list > .ag-virtual-list-viewport > .ag-virtual-list-container > div > .ag-column-select-column").first.click()
    page.get_by_role("treeitem", name="/11(Wed) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("treeitem", name="/12(Thu) Column").get_by_label("Press SPACE to toggle visibility (visible)").uncheck()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.locator("esp-card-component").filter(has_text="Daily Summary Product:THOMAS").get_by_role("button").click()
    page.locator("esp-card-component").filter(has_text="Daily Summary Product:THOMAS").get_by_role("button").click()
    page.get_by_role("treeitem", name="/01(Sun) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/02(Mon) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/03(Tue) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/04(Wed) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/05(Thu) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/06(Fri) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/07(Sat) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/08(Sun) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/09(Mon) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.locator("div:nth-child(10) > .ag-column-select-column").click()
    page.get_by_role("treeitem", name="/11(Wed) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/12(Thu) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/13(Fri) Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (hidden)").check()
    page.locator("esp-card-component").filter(has_text="Daily Summary Product:THOMAS").get_by_role("button").click()
    page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    with page.expect_download() as download3_info:
        page.get_by_text("Please note that a maximum of").click()
    download3 = download3_info.value
    page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("div").filter(has_text=re.compile(r"^Save Preference$")).first.click()
    page.locator("span:nth-child(6) > esp-grid-icons-component > .display-grid-icons > div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("div").filter(has_text=re.compile(r"^Reset Preference$")).first.click()
    page.locator(".ag-header-cell.ag-column-first.ag-header-parent-hidden.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-cell-label").click()
    page.get_by_text("User Suggested Order Total").click()
    page.locator("i").first.click()
    page.get_by_text("User Override Total").click()
    page.get_by_role("gridcell", name=" User Override Total").click()
    page.locator("i").nth(2).click()
    page.locator("esp-column-dimentional-grid").get_by_text("Gross Units (CW-3)").click()
    page.locator("i").nth(5).click()
    page.locator("esp-column-dimentional-grid").get_by_text("Aged Net Units (CW-3)").click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.locator("esp-column-dimentional-grid").get_by_text("Scan Units (CW-3)").click()
    page.locator(".ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-last-left-pinned.ag-column-first.ag-cell-override-normal.notosans-overwrite.no-border.ag-cell-focus > .ag-cell-wrapper > .ag-group-contracted > .zeb-chevron-right").click()
    page.get_by_text("Daily Trend Product:THOMAS").click()
    page.get_by_text("Daily Trend").click()
    page.locator("dp-line-bar-chart").get_by_text("Product:THOMAS BRANDS").click()
    page.locator("dp-line-bar-chart").get_by_text("Product", exact=True).click()
    page.locator("dp-line-bar-chart").get_by_text("THOMAS BRANDS").click()
    page.locator(".ellipses > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("span").filter(has_text="User Suggested Order Base").click()
    page.locator("span").filter(has_text="User Suggested Order Promotion").click()
    page.locator("span").filter(has_text="User Override Base").click()
    page.locator("span").filter(has_text="User Override Promotion").click()
    page.locator("dp-line-bar-chart span").filter(has_text="Gross Units (CW-3)").click()
    page.locator("dp-line-bar-chart").get_by_text("Gross Units (CW-4)").click()
    page.locator("div:nth-child(7) > .d-flex").click()
    page.locator("div:nth-child(8) > .d-flex").click()
    page.locator("div:nth-child(9) > .d-flex").click()
    page.locator("div:nth-child(10) > .d-flex").click()
    page.locator("div:nth-child(11) > .d-flex").click()
    page.locator("div:nth-child(12) > .d-flex").click()
    page.locator("dp-line-bar-chart span").filter(has_text="Scan Units (CW-3)").click()
    page.locator("dp-line-bar-chart").get_by_text("Scan Units (CW-4)").click()
    page.locator("dp-line-bar-chart").get_by_text("Scan Units (CW-5)").click()
    page.locator("dp-line-bar-chart").get_by_text("Scan Units (CW-6)").click()
    page.get_by_text("Gross Units (CW-4), Gross").first.click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator(".title.d-flex.align-items-center.font-size-16.font-weight-bold.nunito.title-color > .grid-icons-container > esp-grid-icons-component > .display-grid-icons > div > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.locator("path:nth-child(81)").click()
    page.get_by_text("User Override Base", exact=True).click()
    page.get_by_text("User Suggested Order Promotion", exact=True).click()
    page.get_by_text("User Override Base", exact=True).click()
    page.get_by_text("User Suggested Order Promotion", exact=True).click()
    page.locator("svg").click()
    page.locator("svg").click()
    page.get_by_text("02/03/2026", exact=True).click()
    page.get_by_text("300K").click()
    page.get_by_text("600K").click()
    page.locator("path:nth-child(57)").click()
    page.locator("path:nth-child(57)").click()
    page.locator("path:nth-child(99)").click()
    page.locator("path:nth-child(98)").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
