import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.mkr.esp.antuit.ai/nglcp/promotions/")
    page.get_by_test_id("promotions-action-button").click()
    page.get_by_text("New Promotion").click()
    page.get_by_test_id("promotionEventName").click()
    page.get_by_test_id("promotionEventName").fill("rh-1205070436")
    page.get_by_test_id("promotionEventDescription").click()
    page.get_by_test_id("promotionEventDescription").fill("PROMO TEST 3")
    page.get_by_test_id("startDate").click()
    page.get_by_text("9").nth(1).click()
    page.get_by_test_id("endDate").click()
    page.get_by_text("12", exact=True).click()
    page.get_by_test_id("isAsapPricing").click()
    page.locator(".zeb-tiers").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Hierarchy$")).nth(3).click()
    page.get_by_text("Region", exact=True).click()
    page.get_by_role("radio", name="NA", exact=True).check()
    page.get_by_text("Price Zone Type").click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").first.click()
    page.get_by_text("Price Zone", exact=True).click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator("div:nth-child(8) > .zeb-tiers").click()
    page.locator("#SideFilterproducthierarchyId").get_by_text("Hierarchy").click()
    page.get_by_text("Style Color").click()
    page.locator("div:nth-child(5) > esp-filter-sub-accordion-v1 > .sub-accordion-element > .fiter-values-container > .filter-options > .filter-values-options > .filter-values.d-flex.align-items-center.p-l-32.p-r-12 > .custom-checkbox-wrapper > .pointer").click()
    page.locator("div:nth-child(6) > .custom-checkbox-wrapper > .pointer").click()
    page.locator("div:nth-child(5) > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator("#optimizationObjective > .multiselect-dropdown > div > .w-100").click()
    page.locator("div").filter(has_text=re.compile(r"^Optimize for Sales Unit$")).nth(1).click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_text("Show More").click()
    page.get_by_role("checkbox", name="Column with Header Selection").check()
    page.get_by_test_id("promotions-action-button").click()
    page.get_by_text("Reset Preferences").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("005")
    page.get_by_role("textbox", name="Search").press("Enter")
    page.locator("a").nth(1).click()
    page.get_by_text("Available Products").click()
    page.locator("div:nth-child(3) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div:nth-child(7) > .d-flex").click()
    page.locator(".ag-center-cols-viewport").click()
    page.locator(".w-100.p-h-16").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32").first.click()
    page.get_by_text("21_Men's Underwear").click()
    page.locator("div:nth-child(2) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div:nth-child(3) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".overflow-auto > div:nth-child(2) > .d-flex").click()
    page.get_by_test_id("complex-filter-apply").click()
    page.locator("#ag-2170-input").check()
    page.get_by_test_id("promotions-action-button").click()
    page.get_by_text("Add").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Reoptimize").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.locator(".dropdown-caret").first.click()
    page.get_by_text("BOGO").click()
    page.locator(".row").first.click()
    page.locator("#numberOfBuyGroups > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^1$")).nth(1).click()
    page.locator("#numberOfUnitsToBuyFromEachGroup > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^1$")).nth(1).click()
    page.get_by_role("textbox", name="Add Value").click()
    page.get_by_role("textbox", name="Add Value").fill("34")
    page.get_by_test_id("group-add").first.click()
    page.get_by_test_id("product-ids").click()
    page.get_by_test_id("product-ids").fill("005DKI004106")
    page.get_by_test_id("save").click()
    page.get_by_test_id("group-add").click()
    page.get_by_test_id("product-ids").click()
    page.get_by_test_id("product-ids").fill("022DKI005106")
    page.get_by_test_id("save").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_test_id("replicate").click()
    page.locator("#attribute_value").click()
    page.locator("#attribute_value").fill("45")
    page.locator("#attribute_value").press("Enter")
    page.locator("#end_date").click()
    page.get_by_text("18").click()
    page.get_by_role("gridcell", name="$ (1.00000)").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
