import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.mkr.esp.antuit.ai/nglcp/promotions/landing-page")
    page.get_by_test_id("promotions-action-button").click()
    page.get_by_text("New Promotion").click()
    page.get_by_test_id("promotionEventName").click()
    page.get_by_test_id("promotionEventName").fill("rh1230-08-04")
    page.get_by_test_id("promotionEventDescription").click()
    page.get_by_test_id("promotionEventDescription").fill("PROMO DISCOUNT TEST")
    page.get_by_test_id("startDate").click()
    page.get_by_text("17").click()
    page.get_by_test_id("endDate").click()
    page.get_by_text("18").click()
    page.get_by_test_id("isAsapPricing").click()
    page.get_by_test_id("price_type_reg").click()
    page.locator(".zeb-tiers").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Hierarchy$")).nth(3).click()
    page.locator(".d-flex.p-l-32").first.click()
    page.get_by_role("radio", name="NA", exact=True).check()
    page.get_by_text("Price Zone Type").click()
    page.locator("div:nth-child(3) > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_text("Price Zone", exact=True).click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").first.click()
    page.get_by_text("Price Zone Type").click()
    page.locator(".pointer.custom-checkbox-checked").first.click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").first.click()
    page.get_by_text("Price Zone", exact=True).click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator("div:nth-child(8) > .zeb-tiers").click()
    page.locator("#SideFilterproducthierarchyId").get_by_text("Hierarchy").click()
    page.get_by_text("Style Color").click()
    page.locator("div:nth-child(5) > esp-filter-sub-accordion-v1 > .sub-accordion-element > .fiter-values-container > .filter-options > .filter-values-options > .filter-values.d-flex.align-items-center.p-l-32.p-r-12 > .custom-checkbox-wrapper > .pointer").click()
    page.locator("div:nth-child(7) > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator("#optimizationObjective > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Optimize Sales Revenue$")).nth(1).click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_test_id("summary-show-more-button").click()
    page.get_by_text("Available Products").click()
    page.locator(".dropdown-caret").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator("div:nth-child(2) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div:nth-child(2) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.locator(".overflow-auto > div:nth-child(2)").click()
    page.locator("div:nth-child(3) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div:nth-child(3) > div > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.get_by_text("203_Logo Knits").click()
    page.get_by_test_id("complex-filter-apply").click()
    page.locator(".ag-row-odd > .ag-cell > .ag-cell-wrapper").first.click()
    page.get_by_test_id("promotions-action-button").click()
    page.get_by_text("Add").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Reoptimize").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.locator(".dropdown-caret").first.click()
    page.locator(".overflow-auto > div:nth-child(2) > .d-flex").click()
    page.locator(".row").first.click()
    page.locator("#off").click()
    page.locator("#off").fill("30")
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_text("Price Zone Adjustment").click()
    page.locator("#rounding_rules_id > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^\.99 RN$")).nth(1).click()
    page.locator("#attribute_value").click()
    page.locator("#attribute_value").fill("35")
    page.locator(".dropdown-caret").first.click()
    page.locator(".dropdown-caret").first.click()
    page.get_by_test_id("replicate-apply").click()
    page.goto("https://stage.mkr.esp.antuit.ai/nglcp/product-level-details/product-details")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
