import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.mkr.esp.antuit.ai/nglcp/promotions/create-promotions")
    page.get_by_test_id("promotionEventName").click()
    page.get_by_test_id("promotionEventName").fill("rh--1137-0904")
    page.get_by_test_id("promotionEventDescription").click()
    page.get_by_test_id("promotionEventDescription").fill("PROMO BUNDLE TEST 2")
    page.get_by_test_id("startDate").click()
    page.get_by_text("16").click()
    page.get_by_test_id("endDate").click()
    page.get_by_text("23", exact=True).click()
    page.get_by_test_id("isAsapPricing").click()
    page.get_by_role("textbox", name="Select Locations").click()
    page.locator("#SideFilterlocationhierarchyId").get_by_text("Hierarchy").click()
    page.get_by_text("Region", exact=True).click()
    page.get_by_role("radio", name="JPN").check()
    page.get_by_text("Price Zone Type").click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").first.click()
    page.get_by_text("Price Zone", exact=True).click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.get_by_role("textbox", name="Select Products").click()
    page.locator("#SideFilterproducthierarchyId").get_by_text("Hierarchy").click()
    page.get_by_text("Style Color").click()
    page.get_by_text("Style Color").click()
    page.locator("div:nth-child(5) > esp-filter-sub-accordion-v1 > .sub-accordion-element > .fiter-values-container > .filter-options > .filter-values-options > .filter-values.d-flex.align-items-center.p-l-32.p-r-12 > .custom-checkbox-wrapper").click()
    page.locator("div:nth-child(5) > esp-filter-sub-accordion-v1 > .sub-accordion-element > .fiter-values-container > .filter-options > .filter-values-options > div:nth-child(2) > .custom-checkbox-wrapper > .pointer").click()
    page.locator(".pointer.custom-checkbox-unchecked").first.click()
    page.locator(".pointer.custom-checkbox-unchecked").first.click()
    page.locator("div").filter(has_text=re.compile(r"^101AKB0201$")).click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator("#optimizationObjective > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("Optimize for Margin Revenue").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_test_id("summary-show-more-button").click()
    page.get_by_text("Available Products").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.locator(".dropdown-caret").first.click()
    page.locator(".overflow-auto > div:nth-child(4)").click()
    page.locator(".flex-grow-1").first.click()
    page.get_by_test_id("group-name-edit-btn").click()
    page.get_by_test_id("name").fill("Watch")
    page.get_by_text("Buy 1 0 Eligible Products Selected Add").click()
    page.get_by_test_id("group-add").click()
    page.get_by_test_id("product-ids").click()
    page.get_by_test_id("product-ids").fill("005DKI0041\n100DKX5271\n100DKX534704\n101AKB0201")
    page.get_by_test_id("save").click()
    page.get_by_role("textbox", name="Add Value").click()
    page.get_by_role("textbox", name="Add Value").fill("35")
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_text("Price Zone Adjustment").click()
    page.locator("#attribute_value").click()
    page.locator("#attribute_value").fill("40")
    page.get_by_test_id("replicate-apply").click()
    page.get_by_role("button", name="Submit All for Approval").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("button", name="Actions").click()
    page.get_by_text("Approve", exact=True).click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Actions").click()
    page.get_by_text("Reject").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Actions").click()
    page.get_by_text("Withdraw", exact=True).click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
