import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.mkr.esp.antuit.ai/nglcp/promotions/create-promotions")
    page.get_by_test_id("promotionEventName").click()
    page.get_by_test_id("promotionEventName").fill("rh--1220--0904")
    page.get_by_test_id("promotionEventDescription").click()
    page.get_by_test_id("promotionEventDescription").fill("PROMO THRESHOLD")
    page.get_by_test_id("startDate").click()
    page.get_by_text("10", exact=True).click()
    page.get_by_test_id("endDate").click()
    page.get_by_text("17").click()
    page.get_by_test_id("isAsapPricing").click()
    page.locator(".zeb-tiers").first.click()
    page.locator("#SideFilterlocationhierarchyId").get_by_text("Hierarchy").click()
    page.get_by_text("Region", exact=True).click()
    page.get_by_role("radio", name="NA", exact=True).check()
    page.get_by_text("Price Zone Type").click()
    page.locator("div").filter(has_text=re.compile(r"^Collection$")).click()
    page.get_by_text("Price Zone", exact=True).click()
    page.get_by_text("1_US Collection").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.get_by_role("textbox", name="Select Products").click()
    page.locator("#SideFilterproducthierarchyId").get_by_text("Hierarchy").click()
    page.get_by_text("Style Color").click()
    page.locator("div:nth-child(5) > esp-filter-sub-accordion-v1 > .sub-accordion-element > .fiter-values-container > .filter-options > .filter-values-options > .filter-values.d-flex.align-items-center.p-l-32.p-r-12 > .custom-checkbox-wrapper").click()
    page.locator("div:nth-child(5) > esp-filter-sub-accordion-v1 > .sub-accordion-element > .fiter-values-container > .filter-options > .filter-values-options > div:nth-child(2) > .custom-checkbox-wrapper > .pointer").click()
    page.locator(".pointer.custom-checkbox-unchecked").first.click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator("#optimizationObjective > .multiselect-dropdown > div > .w-100").click()
    page.locator("div").filter(has_text=re.compile(r"^Optimize for Sales Unit$")).nth(1).click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_text("Available Products").click()
    page.get_by_text("Show More").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.locator(".w-100.p-h-16").first.click()
    page.get_by_text("Bundle").click()
    page.get_by_text("Threshold").click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.get_by_text("What type of promotion(s) would you like to compare? *Max limit 5Promo Type").click()
    page.get_by_test_id("spend_amount").click()
    page.get_by_test_id("spend_amount").fill("5000")
    page.locator("#get").click()
    page.locator("#get").fill("25")
    page.get_by_test_id("create-promotions-next-button").click()
    page.get_by_text("Price Zone Adjustment").click()
    page.get_by_test_id("replicate-apply").click()
    page.goto("https://stage.mkr.esp.antuit.ai/nglcp/product-level-details/product-details")
    page.get_by_role("button", name="Close").click()
    page.get_by_test_id("submit-all-for-approval").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Actions").click()
    page.get_by_text("Approve", exact=True).click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Actions").click()
    page.get_by_text("Reject").click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_role("button", name="Actions").click()
    page.get_by_text("Withdraw", exact=True).click()
    page.get_by_test_id("confirm-modal-confirm-yes-button").click()
    page.get_by_test_id("create-promotions-next-button").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
