import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stage.wba.esp.antuit.ai/dp/demand-planning/executive-dashboard?workbookId=6&tabIndex=1")
    page.locator("#alerts-filterId").click()
    page.locator("div").filter(has_text=re.compile(r"^MAPE$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Under Bias$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Over Bias$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^PVA$")).nth(1).click()
    page.locator(".w-100.p-h-16.p-v-8.dropdown-label.background-white > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^SSIS$")).first.click()
    page.get_by_role("button", name="columns").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="Store Count Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Product Count Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Stability Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="SSIS Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="User Bias Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="System Bias Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="User MAPE Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="System MAPE Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Planner Value Add Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="13W-Fcst Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.locator("div:nth-child(11) > .ag-column-select-column").click()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("Store Count")
    page.get_by_role("textbox", name="Filter Columns Input").press("Enter")
    page.get_by_role("checkbox", name="Press SPACE to toggle").check()
    page.get_by_role("button", name="columns").click()
    page.get_by_role("row", name=" 002-SPIRITS").get_by_role("radio").check()
    page.get_by_title("Filter").first.click()
    page.get_by_role("textbox", name="Filter Value").fill("002-SPIRITS")
    page.get_by_label("Column Filter").get_by_role("button", name="Apply").click()
    page.get_by_title("Filter").first.click()
    page.locator(".ag-icon.ag-icon-small-down").first.click()
    page.get_by_role("option", name="Does not contain").click()
    page.locator(".ag-icon.ag-icon-small-down").first.click()
    page.get_by_role("option", name="Equals").click()
    page.locator(".ag-icon.ag-icon-small-down").first.click()
    page.get_by_role("option", name="Does not equal").click()
    page.locator(".ag-icon.ag-icon-small-down").first.click()
    page.get_by_role("option", name="Begins with").click()
    page.locator(".ag-icon.ag-icon-small-down").first.click()
    page.get_by_role("option", name="Ends with").click()
    page.locator(".ag-icon.ag-icon-small-down").first.click()
    page.get_by_role("option", name="Does not contain").click()
    page.get_by_label("Column Filter").get_by_role("button", name="Apply").click()
    page.get_by_title("Filter").first.click()
    page.get_by_role("button", name="Reset").click()
    page.locator("a").first.click()
    page.locator("a").nth(1).click()
    page.locator(".pagination-next > .zeb-chevron-right").first.click()
    page.locator(".zeb-chevron-left").first.click()
    page.locator(".zeb-nav-to-first").first.click()
    page.locator(".d-flex > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^View 20 row\(s\)$")).first.click()
    page.locator(".d-flex > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^View 50 row\(s\)$")).first.click()
    page.locator(".d-flex > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.locator("div").filter(has_text=re.compile(r"^View 10 row\(s\)$")).nth(1).click()
    page.get_by_text("Locations 20 rows out of 968").click()
    page.locator(".pointer.chevron.zeb-chevron-right.m-r-12.collapsed").click()
    page.get_by_text("Locations", exact=True).click()
    page.get_by_role("row", name="Location").get_by_role("checkbox").uncheck()
    page.get_by_role("button", name="columns").nth(1).click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="Store Count Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Product Count Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="13W-Fcst Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("textbox", name="Filter Columns Input").click()
    page.get_by_role("textbox", name="Filter Columns Input").fill("Pre")
    page.get_by_role("checkbox", name="Press SPACE to toggle").check()
    page.get_by_role("button", name="columns").nth(1).click()
    page.locator("#ag-header-cell-menu-button > .filter-icon").click()
    page.get_by_role("textbox", name="Filter Value").click()
    page.get_by_role("textbox", name="Filter Value").fill("CHICAGO")
    page.get_by_label("Column Menu").get_by_role("button", name="Apply").click()
    page.get_by_role("gridcell", name="00162-1554 E 55TH ST-CHICAGO-").get_by_role("checkbox").check()
    page.locator("#ag-header-cell-menu-button > .filter-icon").click()
    page.get_by_label("Column Menu").get_by_role("button", name="Reset").click()
    page.get_by_role("row", name="Location").get_by_role("checkbox").check()
    page.locator("a").filter(has_text="2").nth(1).click()
    page.locator("a").filter(has_text="3").nth(1).click()
    page.locator("div:nth-child(3) > esp-pagination-v2 > .d-flex.w-100 > .pagination-pager > .pagination-next > .zeb-chevron-right").click()
    page.locator("div:nth-child(3) > esp-pagination-v2 > .d-flex.w-100 > .pagination-pager > .pagination-previous > .zeb-chevron-left").click()
    page.locator("div:nth-child(3) > esp-pagination-v2 > .d-flex.w-100 > .pagination-pager > .pagination-first > .zeb-nav-to-first").click()
    page.get_by_role("button", name="Apply").click()
    page.get_by_text("Filter").nth(2).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 4 Next 4$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 4 Next 13$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 13 Next 13$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 52 Next 52$")).first.click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 104 Next 52$")).nth(1).click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div").filter(has_text=re.compile(r"^Latest 4 Next 4$")).nth(1).click()
    page.locator("#event-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("TLC")
    page.locator(".icon.d-flex.pointer.zeb-close").click()
    page.locator(".not-allowed > .w-100 > .d-flex.align-items-center > .dropdown-caret").first.click()
    page.locator("#ad-location-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator("#ad-location-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#segment-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator("#segment-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#vendor-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".overflow-auto > div:nth-child(2) > .d-flex").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator("#vendor-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("button").filter(has_text=re.compile(r"^Apply$")).click()
    page.locator(".ellipses > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".overflow-auto > div:nth-child(5)").click()
    page.locator(".ellipses > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.get_by_role("button", name="columns").nth(2).click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.locator("#ag-6720 > .ag-column-panel > .ag-column-select > .ag-column-select-list > .ag-virtual-list-viewport > .ag-virtual-list-container > div > .ag-column-select-column").first.click()
    page.get_by_role("treeitem", name="/11/2026 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="/18/2026 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="/25/2026 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="02/01/2026 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="/08/2026 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("button", name="columns").nth(2).click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".overflow-auto > div:nth-child(4) > .d-flex").click()
    page.locator("div:nth-child(5) > .d-flex").click()
    page.get_by_text("Maximum User Forecast").nth(1).click()
    page.get_by_text("Average User Forecast").nth(1).click()
    page.locator(".overflow-auto > div:nth-child(8)").click()
    page.locator(".d-flex.dropdown-option").first.click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("div:nth-child(3) > span > .align-middle").click()
    page.locator(".ag-header-cell.ag-header-parent-hidden.ag-header-cell-sortable.ag-header-background.ag-focus-managed.ag-header-active > .ag-header-cell-comp-wrapper > .ag-cell-label-container > .ag-header-icon > .filter-icon").click()
    page.get_by_label("Column Filter").get_by_role("button", name="Apply").click()
    page.get_by_role("button", name="columns").nth(3).click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="Start Week Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="End Week Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Clone Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Event Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Market Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Count of Stores Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Spot Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").check()
    page.get_by_role("button", name="columns").nth(3).click()
    page.locator("a").filter(has_text="2").nth(2).click()
    page.locator("a").filter(has_text="3").nth(2).click()
    page.locator("div:nth-child(7) > div > .componentParentWrapper > esp-grid-container > esp-card-component > .card-container > .card-content > esp-row-dimentional-grid > div > #paginationId > esp-pagination-v2 > .d-flex.w-100 > .pagination-pager > .pagination-first").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
